accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('delete/', views.delete, name='delete'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('<int:pk>/detail', views.detail, name='detail'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('password/', views.change_password, name='change_password'),
    path('', views.index, name="index"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
]

accounts/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    nickname = models.CharField(max_length=10)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from .models import User

from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username','email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.http import JsonResponse
from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def index(request):
    all = get_user_model().objects.all()
    context = {
        'v':all,
    }
    return render(request,"accounts/index.html",context)
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:   
        form = CustomUserCreationForm()

    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('accounts:index')

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    person = get_object_or_404(get_user_model(), pk=pk)
    context = {
        "person":person,
        'user': user,
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
    'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

boards/views.py
from django.shortcuts import render,redirect

# Create your views here.

games/views.py
from django.shortcuts import render,redirect

# Create your views here.

news/views.py
from django.shortcuts import render,redirect

# Create your views here.

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="text-center my-5">비밀번호 변경</h1>
      <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form%}
        <button type="submit" class="btn btn-dark mt-3">제출</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="my-5 text-center">{{ user.username }}님의 프로필</h1>
      <hr>
      <div class="d-flex">
        <p class="mb-0" style="width:50%;">이메일</p>
        <p class="mb-0" style="width:50%;">{{ user.email }}</p>
      </div>
      <hr>
      <div class="d-flex">
        <p class="mb-0" style="width:50%;">가입 시각</p>
        <p class="mb-0" style="width:50%;">{{ user.date_joined }}</p>
      </div>
      <hr>
      {% if request.user == user %}
        <div class="d-flex justify-content-end">
          <a href="{% url 'accounts:update' %}" class="btn btn-primary mt-3 me-3">나의정보수정</a>
          <a href="{% url 'accounts:delete' %}" class="btn btn-danger mt-3">회원탈퇴</a>
        </div>
      {% endif %}
    </div>
  </div>
  {% endblock%}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center my-5 ">회원 목록</h1>
  <div class='container'>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>회원 번호</th>
          <th scope='col'>회원 이름</th>
          <th scope='col'>이메일</th>
          <th scope='col'>가입일</th>
          <th scope="col">팔로워</th>
          <th scope="col">팔로잉</th>
        </tr>
      </thead>
      <tbody>
        {% for member in v %}
          <tr>
            <th scope='row'>{{ member.id }}</th>
            <td>
              <a href='{% url 'accounts:detail' member.pk %}' class="text-decoration-none text-dark fw-bold">{{ member.username }}</a>
            </td>
            <td>{{ member.email }}</td>
            <td>{{ member.date_joined }}</td>
            <td>{{ member.followers.all|length }}</td>
            <td>{{ member.followings.all|length }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1>로그인</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-dark">제출</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1>회원가입</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-dark">제출</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="text-center my-5">회원 정보 수정</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <a href="{% url 'accounts:change_password' %}" class="btn btn-outline-dark me-3">비밀번호 수정하러 가기</a>
        <button type="submit" class="btn btn-dark">제출</button>
      </form>
    </div>
  </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin"/>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <style>
      * {
        font-family: "Noto Sans KR", sans-serif;
      }

      ul {
        list-style: none;
      }
    </style>
    <title>HOME</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light px-5">
      <div class="container-fluid ">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={% url 'accounts:index' %}>회원 목록</a>
            </li>
            {% if user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link active" href={% url 'accounts:signup' %}>회원가입</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href={% url 'accounts:login' %}>로그인</a>
              </li>
            {% else %}
            {% endif %}
          </ul>
          {% if not user.is_anonymous %}
            <a class="nav-link mx-3" href={% url 'accounts:logout' %}>
              <strong>{{request.user}}</strong>님 로그아웃</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  </body>

</html>